require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'wrestlefeed' do
  config = use_native_modules!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'XCDYouTubeKit', '~> 2.8'

  use_react_native!(:path => config["reactNativePath"])

  target 'wrestlefeedTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'wrestlefeed-tvOS' do
  # Pods for wrestlefeed-tvOS

  target 'wrestlefeed-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
